template-file-path: cf-ec2.yaml
parameters: 
    KeyName: ec2_key_pair
    InstanceType: t2.micro
    SSHLocation: "0.0.0.0/0"
    Subnets: "subnet-09112f6a3a9f6b31f"    
tags:
    cost-center: '123456'
    org: 'AWS'
